export default function handler(req, res) {
  const menu = [
    {
      id: 1,
      name: "Jollof Rice",
      price: 1500,
      image: "/images/pix (6).png",
      category: "Rice",
    },
    {
      id: 2,
      name: "Egusi Soup",
      price: 2500,
      image: "/images/pix (3).png",
      category: "Soups",
    },
    {
      id: 3,
      name: "Yam and Egg",
      price: 1800,
      image: "/images/pix (5).png",
      category: "Snacks",
    },
    {
      id: 4,
      name: "Ogbono Soup",
      price: 2500,
      image: "/images/pix (2).png",
      category: "Soups",
    },
    {
      id: 5,
      name: "Chips and Chicken",
      price: 3000,
      image: "/images/pix (1).png",
      category: "Snacks",
    },
    {
      id: 6,
      name: "Okro Soup",
      price: 2500,
      image: "/images/pix (9).png",
      category: "Soups",
    },
    {
      id: 7,
      name: "Efo riro",
      price: 2500,
      image: "/images/pix (10).png",
      category: "Soups",
    },
    {
      id: 8,
      name: "Pounded Yam with Egusi",
      price: 3500,
      image: "/images/pix (3).png",
      category: "Swallow",
    },
    {
      id: 9,
      name: "Asun Fried Rice",
      price: 2200,
      image: "/images/pix (32).png",
      category: "Rice",
    },
    {
      id: 10,
      name: "Shrimp Fried Rice",
      price: 2200,
      image: "/images/pix (30).png",
      category: "Rice",
    },
    {
      id: 11,
      name: "Native Pasta",
      price: 2200,
      image: "/images/pix (12).png",
      category: "Pasta",
    },
    {
      id: 12,
      name: "Singapore Noodles",
      price: 2200,
      image: "/images/pix (14).png",
      category: "Pasta",
    },
    {
      id: 13,
      name: "Creamy Pasta",
      price: 2200,
      image: "/images/pix (17).png",
      category: "Pasta",
    },
    {
      id: 14,
      name: "Coconut Pasta",
      price: 2200,
      image: "/images/pix (15).png",
      category: "Pasta",
    },
    {
      id: 15,
      name: "Marinara Pasta",
      price: 2200,
      image: "/images/pix (16).png",
      category: "Pasta",
    },
    {
      id: 16,
      name: "Mac and Cheese with Atarodo",
      price: 2200,
      image: "/images/pix (18).png",
      category: "Pasta",
    },
    {
      id: 17,
      name: "Spicy Penne",
      price: 2200,
      image: "/images/pix (11).png",
      category: "Pasta",
    },
    {
      id: 18,
      name: "Spicy Veggie Noodles",
      price: 2200,
      image: "/images/pix (13).png",
      category: "Pasta",
    },
    {
      id: 19,
      name: "Kunu",
      price: 2200,
      image: "/images/pix (20).png",
      category: "Drinks",
    },
    {
      id: 20,
      name: "Zobo",
      price: 2200,
      image: "/images/pix (21).png",
      category: "Drinks",
    },
    {
      id: 21,
      name: "Cocktail Special",
      price: 2200,
      image: "/images/pix (22).png",
      category: "Drinks",
    },
    {
      id: 22,
      name: "Mocktails",
      price: 2200,
      image: "/images/pix (23).png",
      category: "Drinks",
    },
    {
      id: 23,
      name: "Cocktails",
      price: 2200,
      image: "/images/pix (24).png",
      category: "Drinks",
    },
    {
      id: 24,
      name: "MilkShake",
      price: 2200,
      image: "/images/pix (25).png",
      category: "Drinks",
    },
    {
      id: 25,
      name: "Mixxy",
      price: 2200,
      image: "/images/pix (26).png",
      category: "Drinks",
    },
    {
      id: 26,
      name: "Freshy",
      price: 2200,
      image: "/images/pix (27).png",
      category: "Drinks",
    },
    {
      id: 27,
      name: " Fried Rice",
      price: 2200,
      image: "/images/pix (28).png",
      category: "Rice",
    },
    {
      id: 28,
      name: "Amala",
      price: 2200,
      image: "/images/pix (29).png",
      category: "Swallow",
    },
    {
      id: 29,
      name: "Small Chops",
      price: 2200,
      image: "/images/pix (31).png",
      category: "Snacks",
    },
    {
      id: 30,
      name: "Moi Moi",
      price: 2200,
      image: "/images/pix (33).png",
      category: "Sides",
    },
    {
      id: 31,
      name: "Asun Spaghetti",
      price: 2200,
      image: "/images/pix (34).png",
      category: "Pasta",
    },
  ];
  res.status(200).json(menu);
}
